package asia.leadsgen.psp.util;

public class OpenSSLUtilConst {
	public static final String DOMAIN_CONF_TPL = "map $sent_http_content_type $expiresweb {\n"
			+ "    default                    off;\n" + "    text/html                  epoch;\n"
			+ "    text/css                   max;\n" + "    application/javascript     max;\n"
			+ "    ~image/                    max;\n" + "    application/octet-stream   max; \n"
			+ "    application/font-woff      max;\n" + " }\n" + "\n" + "server {\n" + "    listen       80;\n"
			+ "    server_name  www.%s %s;\n" + "    return       301 https://%s$request_uri;\n" + "}\n" + "server {\n"
			+ "	listen 443 http2 ssl;\n" + "  	server_name www.%s;\n" + "\n"
			+ "	ssl_certificate /etc/nginx/ssl/%s/%s.crt;\n" + "    ssl_certificate_key /etc/nginx/ssl/%s/%s.key;\n"
			+ "    \n" + "    return       301 https://%s$request_uri;\n" + "}\n" + "\n" + "server {\n"
			+ "	listen 443 http2 ssl;\n" + "  	server_name %s;\n" + "\n"
			+ "	ssl_certificate /etc/nginx/ssl/%s/%s.crt;\n" + "    ssl_certificate_key /etc/nginx/ssl/%s/%s.key;\n"
			+ "	\n" + "	\n" + "	client_max_body_size 20m;\n" + "    client_body_buffer_size 128k;\n" + "\n"
			+ "  	proxy_read_timeout 2m;\n" + "    \n" + "    ### Set headers ####\n"
			+ "    proxy_set_header        Accept-Encoding   \"\";\n"
			+ "    proxy_set_header        Host            $host;\n"
			+ "    proxy_set_header        X-Real-IP       $remote_addr;\n"
			+ "    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;\n"
			+ "    proxy_set_header        X-Forwarded-Proto $scheme;\n" + "    \n"
			+ "    add_header X-Frame-Options \"SAMEORIGIN\";\n" + "    add_header Access-Control-Allow-Origin *;\n"
			+ "    proxy_redirect off;\n" + "    \n" + "	root /opt/30usd/customdomain/v2/public;    \n" + " \n"
			+ "    #pagespeed on;\n" + "\n" + "    index index.php index.html index.htm;\n" + "    \n"
			+ "    expires $expiresweb;    \n" + "    \n" + "    location / {    	\n"
			+ "    	if ($allowed_country = no) {\n" + "                #return 403;\n" + "		}\n"
			+ "        try_files $uri $uri/ /index.php?$query_string;\n" + "    }\n" + "    \n" + "\n"
			+ "    location /image/social {\n" + "        proxy_redirect off;\n"
			+ "  		rewrite ^/image/social(.*)$ /isp/api/v1/social$1 break;\n"
			+ "        proxy_pass http://127.0.0.1:2180;\n" + "    }\n" + "    \n"
			+ "    location /payments/token/braintree {\n" + "        proxy_redirect off;\n"
			+ "  		rewrite ^/payments/token/braintree /pasp/api/v1/payments/token/braintree break;\n"
			+ "        proxy_pass http://127.0.0.1:5180;\n" + "    }\n" + "    \n" + "    location /promotions {\n"
			+ "        proxy_redirect off;\n" + "  		rewrite ^/promotions /psp/api/v1/promotions break;\n"
			+ "        proxy_pass http://127.0.0.1:1180;\n" + "    }\n" + "    \n" + "    location /analytics {\n"
			+ "        proxy_redirect off;\n" + "  		rewrite ^/analytics /psp/api/v1/traffic_tracking break;\n"
			+ "        proxy_pass http://127.0.0.1:1180;\n" + "    }\n" + "    location /basic_status {\n"
			+ "    		stub_status;\n" + "    }    \n" + "    set $fastcgi_skipcache 0;\n" + " \n"
			+ "	if ($query_string) {\n" + "		set $fastcgi_skipcache 1;\n" + "	}\n" + " \n"
			+ "	if ($http_x_custom_header) {\n" + "		set $fastcgi_skipcache 0;\n" + "	}\n" + " \n"
			+ "	if ($uri ~ \"/shop/cart\") {\n" + "		set $fastcgi_skipcache 1;\n" + "	}\n"
			+ "	if ($uri ~ \"/shop/checkout\") {\n" + "		set $fastcgi_skipcache 1;\n" + "	}\n"
			+ "	if ($uri ~ \"/shop/thankyou\") {\n" + "		set $fastcgi_skipcache 1;\n" + "	}\n"
			+ "	if ($uri ~ \"/contact/\") {\n" + "		set $fastcgi_skipcache 1;\n" + "	}\n" + " \n"
			+ "	if ($http_cookie ~ \"users_login_cookie\") {\n" + "		set $fastcgi_skipcache 1;\n" + "	}    \n"
			+ "    location ~ \\.php$ {\n" + "    	try_files $uri /index.php =404;\n"
			+ "        fastcgi_split_path_info ^(.+\\.php)(/.+)$;\n" + "        \n"
			+ "        #add_header X-Cache $upstream_cache_status;\n" + "	#fastcgi_cache fastcgicache;\n"
			+ "	#fastcgi_cache_bypass $fastcgi_skipcache;\n" + "	#fastcgi_no_cache $fastcgi_skipcache;\n" + "\n"
			+ "        fastcgi_pass 127.0.0.1:9000;\n" + "        #fastcgi_pass unix:/var/run/php-fpm.sock;\n"
			+ "        fastcgi_index index.php;\n" + "        fastcgi_read_timeout 300;\n"
			+ "	#include fastcgi.conf;\n"
			+ "        fastcgi_param	SCRIPT_FILENAME $document_root$fastcgi_script_name;\n"
			+ "        fastcgi_param	PATH_INFO $fastcgi_path_info;\n"
			+ "        fastcgi_param	PATH_TRANSLATED $document_root$fastcgi_path_info;\n"
			+ "        include fastcgi_params;    \n" + "    }\n" + "    location ~ /\\. {\n"
			+ "    	access_log off;\n" + "    	log_not_found off; \n" + "    	deny all;\n" + "	}\n" + "    \n"
			+ "}\n";

}
